/* This file is auto-generated by InSpatial ORM. Do not edit manually. */
import type { EntryBase } from "../orm/entry/entry-base.ts";
import type { ChildEntryList as ChildList } from "../orm/child-entry/child-entry.ts";
import type { SettingsBase } from "../orm/settings/settings-base.ts";

type UserFields = {
  /**
   * **First Name** (DataField)
   * @description The user's first name
   * @type {string}
   * @required true
   */
  firstName: string;
  /**
   * **Last Name** (DataField)
   * @description The user's last names
   * @type {string}
   * @required true
   */
  lastName: string;
  /**
   * **Email** (EmailField)
   * @description The user's email address used for login
   * @type {string}
   * @required true
   */
  email: string;
  /**
   * **Full Name** (DataField)
   * @description The user's full name (automatically generated)
   * @type {string}
   */
  fullName?: string;
  /**
   * **Profile Picture** (ImageField)
   * @description The user's profile picture
   * @type {string}
   */
  profilePicture?: string;
  /**
   * **Password** (PasswordField)
   * @description The user's password used for login
   * @type {string}
   */
  password?: string;
  /**
   * **Reset Password Token** (PasswordField)
   * @description The token used to reset the user's password
   * @type {string}
   */
  resetPasswordToken?: string;
  /**
   * **System Administrator** (BooleanField)
   * @description Is the user a system administrator? (admin users have access to all parts of the system)
   * @type {boolean}
   */
  systemAdmin: boolean;
  /**
   * **Enabled** (BooleanField)
   * @description Is the user account enabled? Disabled accounts cannot log in.
   * @type {boolean}
   */
  enabled: boolean;
  /**
   * **API Token** (PasswordField)
   * @description The user's API token
   * @type {string}
   */
  apiToken?: string;
  /**
   * **Access Token** (PasswordField)
   * @description The access token used to authenticate the user with Google.
   * @type {string}
   */
  googleAccessToken?: string;
  /**
   * **Refresh Token** (PasswordField)
   * @description The refresh token used to refresh the access token.
   * @type {string}
   */
  googleRefreshToken?: string;
  /**
   * **Google Credential** (JSONField)
   * @description The credential used to authenticate the user with Google.
   * @type {Record<string, any>}
   */
  googleCredential?: Record<string, any>;
  /**
   * **Google ID** (TextField)
   * @description The user's Google ID.
   * @type {string}
   */
  googleId?: string;
  /**
   * **Google Picture** (URLField)
   * @description The user's Google profile picture.
   * @type {string}
   */
  googlePicture?: string;
  /**
   * **Google Auth Status** (ChoicesField)
   * @type {'authenticated' | 'notAuthenticated'}
   */
  googleAuthStatus?: "authenticated" | "notAuthenticated";
  /**
   * **ID** (IDField)
   * @type {string}
   * @required true
   */
  id: string;
  /**
   * **Created At** (TimeStampField)
   * @description The date and time this entry was created
   * @type {number}
   * @required true
   */
  createdAt: number;
  /**
   * **Updated At** (TimeStampField)
   * @description The date and time this entry was last updated
   * @type {number}
   * @required true
   */
  updatedAt: number;
  /**
   * **Tags** (ArrayField)
   * @description Tags associated with this User
   * @type {Array<any>}
   */
  in__tags?: Array<any>;
  /**
   * **Profile Picture Title** (DataField)
   * @type {string}
   */
  profilePicture__title?: string;
};
export type User = EntryBase<UserFields> & {
  _name: "user";
  __fields__: UserFields;
  /**
   * **First Name** (DataField)
   * @description The user's first name
   * @type {string}
   * @required true
   */
  $firstName: string;
  /**
   * **Last Name** (DataField)
   * @description The user's last names
   * @type {string}
   * @required true
   */
  $lastName: string;
  /**
   * **Email** (EmailField)
   * @description The user's email address used for login
   * @type {string}
   * @required true
   */
  $email: string;
  /**
   * **Full Name** (DataField)
   * @description The user's full name (automatically generated)
   * @type {string}
   */
  $fullName?: string;
  /**
   * **Profile Picture** (ImageField)
   * @description The user's profile picture
   * @type {string}
   */
  $profilePicture?: string;
  /**
   * **Password** (PasswordField)
   * @description The user's password used for login
   * @type {string}
   */
  $password?: string;
  /**
   * **Reset Password Token** (PasswordField)
   * @description The token used to reset the user's password
   * @type {string}
   */
  $resetPasswordToken?: string;
  /**
   * **System Administrator** (BooleanField)
   * @description Is the user a system administrator? (admin users have access to all parts of the system)
   * @type {boolean}
   */
  $systemAdmin: boolean;
  /**
   * **Enabled** (BooleanField)
   * @description Is the user account enabled? Disabled accounts cannot log in.
   * @type {boolean}
   */
  $enabled: boolean;
  /**
   * **API Token** (PasswordField)
   * @description The user's API token
   * @type {string}
   */
  $apiToken?: string;
  /**
   * **Access Token** (PasswordField)
   * @description The access token used to authenticate the user with Google.
   * @type {string}
   */
  $googleAccessToken?: string;
  /**
   * **Refresh Token** (PasswordField)
   * @description The refresh token used to refresh the access token.
   * @type {string}
   */
  $googleRefreshToken?: string;
  /**
   * **Google Credential** (JSONField)
   * @description The credential used to authenticate the user with Google.
   * @type {Record<string, any>}
   */
  $googleCredential?: Record<string, any>;
  /**
   * **Google ID** (TextField)
   * @description The user's Google ID.
   * @type {string}
   */
  $googleId?: string;
  /**
   * **Google Picture** (URLField)
   * @description The user's Google profile picture.
   * @type {string}
   */
  $googlePicture?: string;
  /**
   * **Google Auth Status** (ChoicesField)
   * @type {'authenticated' | 'notAuthenticated'}
   */
  $googleAuthStatus?: "authenticated" | "notAuthenticated";
  /**
   * **ID** (IDField)
   * @type {string}
   * @required true
   */
  $id: string;
  /**
   * **Created At** (TimeStampField)
   * @description The date and time this entry was created
   * @type {number}
   * @required true
   */
  $createdAt: number;
  /**
   * **Updated At** (TimeStampField)
   * @description The date and time this entry was last updated
   * @type {number}
   * @required true
   */
  $updatedAt: number;
  /**
   * **Tags** (ArrayField)
   * @description Tags associated with this User
   * @type {Array<any>}
   */
  $in__tags?: Array<any>;
  /**
   * **Profile Picture Title** (DataField)
   * @type {string}
   */
  $profilePicture__title?: string;
  isFieldModified(
    fieldKey: keyof {
      [K in keyof User as K extends keyof EntryBase ? never : K]: K;
    },
  ): boolean;
  runAction<N extends keyof UserActionMap>(
    actionName: N,
  ): UserActionMap[N]["return"];
  runAction<N extends keyof UserParamsActionMap>(
    actionName: N,
    params: UserParamsActionMap[N]["params"],
  ): UserParamsActionMap[N]["return"];
};
type UserActionMap = {
  generateApiToken: {
    return: Promise<any>;
  };
  generateResetToken: {
    return: Promise<any>;
  };
  findAccounts: {
    return: Promise<any>;
  };
};
type UserParamsActionMap = {
  setPassword: {
    params: {
      /**
       * **Password** (PasswordField)
       * @description Password to set
       * @type {string}
       * @required true
       */
      password: string;
    };
    return: Promise<any>;
  };
  validatePassword: {
    params: {
      /**
       * **Password** (PasswordField)
       * @description Password to validate
       * @type {string}
       * @required true
       */
      password: string;
    };
    return: Promise<any>;
  };
};

type UserSessionFields = {
  /**
   * **User** (ConnectionField)
   *
   * **EntryType** `user`
   * @description The user associated with this session
   * @type {string}
   * @required true
   */
  user: string;
  /**
   * **Session ID** (DataField)
   * @description Unique identifier for the session
   * @type {string}
   * @required true
   */
  sessionId: string;
  /**
   * **Session Data** (JSONField)
   * @description Data associated with the session
   * @type {Record<string, any>}
   */
  sessionData?: Record<string, any>;
  /**
   * **User Session** (IDField)
   * @type {string}
   * @required true
   */
  id: string;
  /**
   * **Created At** (TimeStampField)
   * @description The date and time this entry was created
   * @type {number}
   * @required true
   */
  createdAt: number;
  /**
   * **Updated At** (TimeStampField)
   * @description The date and time this entry was last updated
   * @type {number}
   * @required true
   */
  updatedAt: number;
  /**
   * **Tags** (ArrayField)
   * @description Tags associated with this User Session
   * @type {Array<any>}
   */
  in__tags?: Array<any>;
  /**
   * **User Title** (DataField)
   * @description The user's full name (automatically generated)
   * @type {string}
   */
  user__title?: string;
};
export type UserSession = EntryBase<UserSessionFields> & {
  _name: "userSession";
  __fields__: UserSessionFields;
  /**
   * **User** (ConnectionField)
   *
   * **EntryType** `user`
   * @description The user associated with this session
   * @type {string}
   * @required true
   */
  $user: string;
  /**
   * **Session ID** (DataField)
   * @description Unique identifier for the session
   * @type {string}
   * @required true
   */
  $sessionId: string;
  /**
   * **Session Data** (JSONField)
   * @description Data associated with the session
   * @type {Record<string, any>}
   */
  $sessionData?: Record<string, any>;
  /**
   * **User Session** (IDField)
   * @type {string}
   * @required true
   */
  $id: string;
  /**
   * **Created At** (TimeStampField)
   * @description The date and time this entry was created
   * @type {number}
   * @required true
   */
  $createdAt: number;
  /**
   * **Updated At** (TimeStampField)
   * @description The date and time this entry was last updated
   * @type {number}
   * @required true
   */
  $updatedAt: number;
  /**
   * **Tags** (ArrayField)
   * @description Tags associated with this User Session
   * @type {Array<any>}
   */
  $in__tags?: Array<any>;
  /**
   * **User Title** (DataField)
   * @description The user's full name (automatically generated)
   * @type {string}
   */
  $user__title?: string;
  isFieldModified(
    fieldKey: keyof {
      [K in keyof UserSession as K extends keyof EntryBase ? never : K]: K;
    },
  ): boolean;
};

type AccountFields = {
  /**
   * **Account Owner** (ConnectionField)
   *
   * **EntryType** `user`
   * @description The user who owns this account. Only one user can be the owner.
   * @type {string}
   */
  owner?: string;
  /**
   * **Account Name** (DataField)
   * @description The name of the account
   * @type {string}
   * @required true
   */
  name: string;
  /**
   * **Onboarding Complete** (BooleanField)
   * @type {boolean}
   */
  onboardingComplete: boolean;
  /**
   * **Initialized** (BooleanField)
   * @type {boolean}
   */
  initialized: boolean;
  /**
   * **Onboarding Response** (JSONField)
   * @type {Record<string, any>}
   */
  obResponse?: Record<string, any>;
  /**
   * **Account** (IDField)
   * @type {string}
   * @required true
   */
  id: string;
  /**
   * **Created At** (TimeStampField)
   * @description The date and time this entry was created
   * @type {number}
   * @required true
   */
  createdAt: number;
  /**
   * **Updated At** (TimeStampField)
   * @description The date and time this entry was last updated
   * @type {number}
   * @required true
   */
  updatedAt: number;
  /**
   * **Tags** (ArrayField)
   * @description Tags associated with this Account
   * @type {Array<any>}
   */
  in__tags?: Array<any>;
  /**
   * **Account Owner Title** (DataField)
   * @description The user's full name (automatically generated)
   * @type {string}
   */
  owner__title?: string;
  users: ChildList<{
    /**
     * **User** (ConnectionField)
     *
     * **EntryType** `user`
     * @type {string}
     * @required true
     */
    user: string;
    /**
     * **Role** (ConnectionField)
     *
     * **EntryType** `userRole`
     * @type {string}
     */
    role?: string;
    /**
     * **Is Owner** (BooleanField)
     * @type {boolean}
     */
    isOwner: boolean;
    /**
     * **ID** (IDField)
     * @type {string}
     * @required true
     */
    id: string;
    /**
     * **Order** (IntField)
     * @description The order of this child in the list
     * @type {number}
     */
    order?: number;
    /**
     * **Created At** (TimeStampField)
     * @description The date and time this child was created
     * @type {number}
     * @required true
     */
    createdAt: number;
    /**
     * **Updated At** (TimeStampField)
     * @description The date and time this child was last updated
     * @type {number}
     * @required true
     */
    updatedAt: number;
    /**
     * **Parent** (ConnectionField)
     *
     * **EntryType** `account`
     * @type {string}
     * @required true
     */
    parent: string;
    /**
     * **User Title** (DataField)
     * @description The user's full name (automatically generated)
     * @type {string}
     */
    user__title?: string;
    /**
     * **Role Title** (DataField)
     * @type {string}
     */
    role__title?: string;
    /**
     * **Parent Title** (DataField)
     * @description The name of the account
     * @type {string}
     */
    parent__title?: string;
  }>;
};
export type Account = EntryBase<AccountFields> & {
  _name: "account";
  __fields__: AccountFields;
  /**
   * **Account Owner** (ConnectionField)
   *
   * **EntryType** `user`
   * @description The user who owns this account. Only one user can be the owner.
   * @type {string}
   */
  $owner?: string;
  /**
   * **Account Name** (DataField)
   * @description The name of the account
   * @type {string}
   * @required true
   */
  $name: string;
  /**
   * **Onboarding Complete** (BooleanField)
   * @type {boolean}
   */
  $onboardingComplete: boolean;
  /**
   * **Initialized** (BooleanField)
   * @type {boolean}
   */
  $initialized: boolean;
  /**
   * **Onboarding Response** (JSONField)
   * @type {Record<string, any>}
   */
  $obResponse?: Record<string, any>;
  /**
   * **Account** (IDField)
   * @type {string}
   * @required true
   */
  $id: string;
  /**
   * **Created At** (TimeStampField)
   * @description The date and time this entry was created
   * @type {number}
   * @required true
   */
  $createdAt: number;
  /**
   * **Updated At** (TimeStampField)
   * @description The date and time this entry was last updated
   * @type {number}
   * @required true
   */
  $updatedAt: number;
  /**
   * **Tags** (ArrayField)
   * @description Tags associated with this Account
   * @type {Array<any>}
   */
  $in__tags?: Array<any>;
  /**
   * **Account Owner Title** (DataField)
   * @description The user's full name (automatically generated)
   * @type {string}
   */
  $owner__title?: string;
  isFieldModified(
    fieldKey: keyof {
      [K in keyof Account as K extends keyof EntryBase ? never : K]: K;
    },
  ): boolean;
  $users: ChildList<{
    /**
     * **User** (ConnectionField)
     *
     * **EntryType** `user`
     * @type {string}
     * @required true
     */
    user: string;
    /**
     * **Role** (ConnectionField)
     *
     * **EntryType** `userRole`
     * @type {string}
     */
    role?: string;
    /**
     * **Is Owner** (BooleanField)
     * @type {boolean}
     */
    isOwner: boolean;
    /**
     * **ID** (IDField)
     * @type {string}
     * @required true
     */
    id: string;
    /**
     * **Order** (IntField)
     * @description The order of this child in the list
     * @type {number}
     */
    order?: number;
    /**
     * **Created At** (TimeStampField)
     * @description The date and time this child was created
     * @type {number}
     * @required true
     */
    createdAt: number;
    /**
     * **Updated At** (TimeStampField)
     * @description The date and time this child was last updated
     * @type {number}
     * @required true
     */
    updatedAt: number;
    /**
     * **Parent** (ConnectionField)
     *
     * **EntryType** `account`
     * @type {string}
     * @required true
     */
    parent: string;
    /**
     * **User Title** (DataField)
     * @description The user's full name (automatically generated)
     * @type {string}
     */
    user__title?: string;
    /**
     * **Role Title** (DataField)
     * @type {string}
     */
    role__title?: string;
    /**
     * **Parent Title** (DataField)
     * @description The name of the account
     * @type {string}
     */
    parent__title?: string;
  }>;
  runAction<N extends keyof AccountActionMap>(
    actionName: N,
  ): AccountActionMap[N]["return"];
  runAction<N extends keyof AccountParamsActionMap>(
    actionName: N,
    params: AccountParamsActionMap[N]["params"],
  ): AccountParamsActionMap[N]["return"];
};
type AccountActionMap = {
  queueInitialize: {
    return: Promise<any>;
  };
  initialize: {
    return: Promise<any>;
  };
};
type AccountParamsActionMap = {
  addUser: {
    params: {
      /**
       * **First Name** (DataField)
       * @type {string}
       * @required true
       */
      firstName: string;
      /**
       * **Last Name** (DataField)
       * @type {string}
       * @required true
       */
      lastName: string;
      /**
       * **Email** (DataField)
       * @type {string}
       * @required true
       */
      email: string;
      /**
       * **Role** (ConnectionField)
       *
       * **EntryType** `userRole`
       * @type {string}
       * @required true
       */
      role: string;
    };
    return: Promise<any>;
  };
};

type InTaskGlobalFields = {
  /**
   * **Title** (DataField)
   * @type {string}
   * @required true
   */
  title: string;
  /**
   * **Task Type** (ChoicesField)
   * @type {'entry' | 'settings'}
   * @required true
   */
  taskType: "entry" | "settings";
  /**
   * **Entry/Settings Name** (DataField)
   * @type {string}
   */
  typeKey?: string;
  /**
   * **Entry ID** (DataField)
   * @description The ID of the entry to run the action on
   * @type {string}
   */
  entryId?: string;
  /**
   * **Group** (DataField)
   * @type {string}
   */
  group?: string;
  /**
   * **Action Name** (DataField)
   * @type {string}
   * @required true
   */
  actionName: string;
  /**
   * **Status** (ChoicesField)
   * @type {'queued' | 'running' | 'cancelled' | 'completed' | 'failed'}
   * @required true
   */
  status: "queued" | "running" | "cancelled" | "completed" | "failed";
  /**
   * **Start Time** (TimeStampField)
   * @type {number}
   */
  startTime?: number;
  /**
   * **End Time** (TimeStampField)
   * @type {number}
   */
  endTime?: number;
  /**
   * **Task Data** (JSONField)
   * @type {Record<string, any>}
   */
  taskData?: Record<string, any>;
  /**
   * **Result Data** (JSONField)
   * @type {Record<string, any>}
   */
  resultData?: Record<string, any>;
  /**
   * **Error Info** (TextField)
   * @type {string}
   */
  errorInfo?: string;
  /**
   * **InTask Global** (IDField)
   * @type {string}
   * @required true
   */
  id: string;
  /**
   * **Created At** (TimeStampField)
   * @description The date and time this entry was created
   * @type {number}
   * @required true
   */
  createdAt: number;
  /**
   * **Updated At** (TimeStampField)
   * @description The date and time this entry was last updated
   * @type {number}
   * @required true
   */
  updatedAt: number;
  /**
   * **Tags** (ArrayField)
   * @description Tags associated with this InTask Global
   * @type {Array<any>}
   */
  in__tags?: Array<any>;
};
export type InTaskGlobal = EntryBase<InTaskGlobalFields> & {
  _name: "inTaskGlobal";
  __fields__: InTaskGlobalFields;
  /**
   * **Title** (DataField)
   * @type {string}
   * @required true
   */
  $title: string;
  /**
   * **Task Type** (ChoicesField)
   * @type {'entry' | 'settings'}
   * @required true
   */
  $taskType: "entry" | "settings";
  /**
   * **Entry/Settings Name** (DataField)
   * @type {string}
   */
  $typeKey?: string;
  /**
   * **Entry ID** (DataField)
   * @description The ID of the entry to run the action on
   * @type {string}
   */
  $entryId?: string;
  /**
   * **Group** (DataField)
   * @type {string}
   */
  $group?: string;
  /**
   * **Action Name** (DataField)
   * @type {string}
   * @required true
   */
  $actionName: string;
  /**
   * **Status** (ChoicesField)
   * @type {'queued' | 'running' | 'cancelled' | 'completed' | 'failed'}
   * @required true
   */
  $status: "queued" | "running" | "cancelled" | "completed" | "failed";
  /**
   * **Start Time** (TimeStampField)
   * @type {number}
   */
  $startTime?: number;
  /**
   * **End Time** (TimeStampField)
   * @type {number}
   */
  $endTime?: number;
  /**
   * **Task Data** (JSONField)
   * @type {Record<string, any>}
   */
  $taskData?: Record<string, any>;
  /**
   * **Result Data** (JSONField)
   * @type {Record<string, any>}
   */
  $resultData?: Record<string, any>;
  /**
   * **Error Info** (TextField)
   * @type {string}
   */
  $errorInfo?: string;
  /**
   * **InTask Global** (IDField)
   * @type {string}
   * @required true
   */
  $id: string;
  /**
   * **Created At** (TimeStampField)
   * @description The date and time this entry was created
   * @type {number}
   * @required true
   */
  $createdAt: number;
  /**
   * **Updated At** (TimeStampField)
   * @description The date and time this entry was last updated
   * @type {number}
   * @required true
   */
  $updatedAt: number;
  /**
   * **Tags** (ArrayField)
   * @description Tags associated with this InTask Global
   * @type {Array<any>}
   */
  $in__tags?: Array<any>;
  isFieldModified(
    fieldKey: keyof {
      [K in keyof InTaskGlobal as K extends keyof EntryBase ? never : K]: K;
    },
  ): boolean;
  runAction<N extends keyof InTaskGlobalActionMap>(
    actionName: N,
  ): InTaskGlobalActionMap[N]["return"];
};
type InTaskGlobalActionMap = {
  runTask: {
    return: Promise<any>;
  };
};

type InTaskFields = {
  /**
   * **Title** (DataField)
   * @type {string}
   * @required true
   */
  title: string;
  /**
   * **Task Type** (ChoicesField)
   * @type {'entry' | 'settings'}
   * @required true
   */
  taskType: "entry" | "settings";
  /**
   * **Entry/Settings Name** (DataField)
   * @type {string}
   */
  typeKey?: string;
  /**
   * **Entry ID** (DataField)
   * @description The ID of the entry to run the action on
   * @type {string}
   */
  entryId?: string;
  /**
   * **Group** (DataField)
   * @type {string}
   */
  group?: string;
  /**
   * **Action Name** (DataField)
   * @type {string}
   * @required true
   */
  actionName: string;
  /**
   * **Status** (ChoicesField)
   * @type {'queued' | 'running' | 'cancelled' | 'completed' | 'failed'}
   * @required true
   */
  status: "queued" | "running" | "cancelled" | "completed" | "failed";
  /**
   * **Start Time** (TimeStampField)
   * @type {number}
   */
  startTime?: number;
  /**
   * **End Time** (TimeStampField)
   * @type {number}
   */
  endTime?: number;
  /**
   * **Task Data** (JSONField)
   * @type {Record<string, any>}
   */
  taskData?: Record<string, any>;
  /**
   * **Result Data** (JSONField)
   * @type {Record<string, any>}
   */
  resultData?: Record<string, any>;
  /**
   * **Error Info** (TextField)
   * @type {string}
   */
  errorInfo?: string;
  /**
   * **InTask** (IDField)
   * @type {string}
   * @required true
   */
  id: string;
  /**
   * **Created At** (TimeStampField)
   * @description The date and time this entry was created
   * @type {number}
   * @required true
   */
  createdAt: number;
  /**
   * **Updated At** (TimeStampField)
   * @description The date and time this entry was last updated
   * @type {number}
   * @required true
   */
  updatedAt: number;
  /**
   * **Tags** (ArrayField)
   * @description Tags associated with this InTask
   * @type {Array<any>}
   */
  in__tags?: Array<any>;
};
export type InTask = EntryBase<InTaskFields> & {
  _name: "inTask";
  __fields__: InTaskFields;
  /**
   * **Title** (DataField)
   * @type {string}
   * @required true
   */
  $title: string;
  /**
   * **Task Type** (ChoicesField)
   * @type {'entry' | 'settings'}
   * @required true
   */
  $taskType: "entry" | "settings";
  /**
   * **Entry/Settings Name** (DataField)
   * @type {string}
   */
  $typeKey?: string;
  /**
   * **Entry ID** (DataField)
   * @description The ID of the entry to run the action on
   * @type {string}
   */
  $entryId?: string;
  /**
   * **Group** (DataField)
   * @type {string}
   */
  $group?: string;
  /**
   * **Action Name** (DataField)
   * @type {string}
   * @required true
   */
  $actionName: string;
  /**
   * **Status** (ChoicesField)
   * @type {'queued' | 'running' | 'cancelled' | 'completed' | 'failed'}
   * @required true
   */
  $status: "queued" | "running" | "cancelled" | "completed" | "failed";
  /**
   * **Start Time** (TimeStampField)
   * @type {number}
   */
  $startTime?: number;
  /**
   * **End Time** (TimeStampField)
   * @type {number}
   */
  $endTime?: number;
  /**
   * **Task Data** (JSONField)
   * @type {Record<string, any>}
   */
  $taskData?: Record<string, any>;
  /**
   * **Result Data** (JSONField)
   * @type {Record<string, any>}
   */
  $resultData?: Record<string, any>;
  /**
   * **Error Info** (TextField)
   * @type {string}
   */
  $errorInfo?: string;
  /**
   * **InTask** (IDField)
   * @type {string}
   * @required true
   */
  $id: string;
  /**
   * **Created At** (TimeStampField)
   * @description The date and time this entry was created
   * @type {number}
   * @required true
   */
  $createdAt: number;
  /**
   * **Updated At** (TimeStampField)
   * @description The date and time this entry was last updated
   * @type {number}
   * @required true
   */
  $updatedAt: number;
  /**
   * **Tags** (ArrayField)
   * @description Tags associated with this InTask
   * @type {Array<any>}
   */
  $in__tags?: Array<any>;
  isFieldModified(
    fieldKey: keyof {
      [K in keyof InTask as K extends keyof EntryBase ? never : K]: K;
    },
  ): boolean;
  runAction<N extends keyof InTaskActionMap>(
    actionName: N,
  ): InTaskActionMap[N]["return"];
};
type InTaskActionMap = {
  runTask: {
    return: Promise<any>;
  };
};

type CloudFileFields = {
  /**
   * **File Name** (DataField)
   * @type {string}
   * @required true
   */
  fileName: string;
  /**
   * **File Size** (IntField)
   * @type {number}
   * @required true
   */
  fileSize: number;
  /**
   * **File Type** (ChoicesField)
   * @type {'audio' | 'image' | 'video' | 'document' | 'application' | 'code' | 'text' | 'font' | 'archive' | 'unknown'}
   * @required true
   */
  fileType:
    | "audio"
    | "image"
    | "video"
    | "document"
    | "application"
    | "code"
    | "text"
    | "font"
    | "archive"
    | "unknown";
  /**
   * **File Extension** (ChoicesField)
   * @type {'aac' | 'apng' | 'avif' | 'avi' | 'azw' | 'bin' | 'bmp' | 'csh' | 'css' | 'csv' | 'doc' | 'docx' | 'eot' | 'epub' | 'gz' | 'gif' | 'htm' | 'html' | 'ico' | 'ics' | 'jar' | 'jpeg' | 'jpg' | 'js' | 'json' | 'jsonld' | 'mid' | 'midi' | 'mjs' | 'mp3' | 'mp4' | 'mpeg' | 'mpkg' | 'odp' | 'ods' | 'odt' | 'oga' | 'ogv' | 'ogx' | 'opus' | 'otf' | 'png' | 'pdf' | 'php' | 'ppt' | 'pptx' | 'rar' | 'rtf' | 'sh' | 'svg' | 'tar' | 'tif' | 'tiff' | 'ts' | 'ttf' | 'txt' | 'wav' | 'weba' | 'webm' | 'webp' | 'woff' | 'woff2' | 'xhtml' | 'xls' | 'xlsx' | 'xml' | 'zip' | 'arc'}
   */
  fileExtension?:
    | "aac"
    | "apng"
    | "avif"
    | "avi"
    | "azw"
    | "bin"
    | "bmp"
    | "csh"
    | "css"
    | "csv"
    | "doc"
    | "docx"
    | "eot"
    | "epub"
    | "gz"
    | "gif"
    | "htm"
    | "html"
    | "ico"
    | "ics"
    | "jar"
    | "jpeg"
    | "jpg"
    | "js"
    | "json"
    | "jsonld"
    | "mid"
    | "midi"
    | "mjs"
    | "mp3"
    | "mp4"
    | "mpeg"
    | "mpkg"
    | "odp"
    | "ods"
    | "odt"
    | "oga"
    | "ogv"
    | "ogx"
    | "opus"
    | "otf"
    | "png"
    | "pdf"
    | "php"
    | "ppt"
    | "pptx"
    | "rar"
    | "rtf"
    | "sh"
    | "svg"
    | "tar"
    | "tif"
    | "tiff"
    | "ts"
    | "ttf"
    | "txt"
    | "wav"
    | "weba"
    | "webm"
    | "webp"
    | "woff"
    | "woff2"
    | "xhtml"
    | "xls"
    | "xlsx"
    | "xml"
    | "zip"
    | "arc";
  /**
   * **Mime Type** (DataField)
   * @type {string}
   */
  mimeType?: string;
  /**
   * **File Type Description** (DataField)
   * @type {string}
   */
  fileTypeDescription?: string;
  /**
   * **File Path** (TextField)
   * @type {string}
   * @required true
   */
  filePath: string;
  /**
   * **Public File** (BooleanField)
   * @description If enabled, this file can be accessed publicly without authentication.
   * @type {boolean}
   */
  publicFile: boolean;
  /**
   * **Optimize Image** (BooleanField)
   * @description If enabled, images will be optimized
   * @type {boolean}
   */
  optimizeImage: boolean;
  /**
   * **Optimized** (BooleanField)
   * @description Indicates if the image has been optimized.
   * @type {boolean}
   */
  optimized: boolean;
  /**
   * **Optimize Width** (IntField)
   * @type {number}
   */
  optimizeWidth?: number;
  /**
   * **Optimize Height** (IntField)
   * @type {number}
   */
  optimizeHeight?: number;
  /**
   * **Optimize Format** (ChoicesField)
   * @type {'jpeg' | 'png'}
   */
  optimizeFormat?: "jpeg" | "png";
  /**
   * **Has Thumbnail** (BooleanField)
   * @type {boolean}
   */
  hasThumbnail: boolean;
  /**
   * **Thumbnail Size** (IntField)
   * @type {number}
   */
  thumbnailSize?: number;
  /**
   * **Thumbnail Path** (TextField)
   * @type {string}
   */
  thumbnailPath?: string;
  /**
   * **File** (IDField)
   * @type {string}
   * @required true
   */
  id: string;
  /**
   * **Created At** (TimeStampField)
   * @description The date and time this entry was created
   * @type {number}
   * @required true
   */
  createdAt: number;
  /**
   * **Updated At** (TimeStampField)
   * @description The date and time this entry was last updated
   * @type {number}
   * @required true
   */
  updatedAt: number;
  /**
   * **Tags** (ArrayField)
   * @description Tags associated with this File
   * @type {Array<any>}
   */
  in__tags?: Array<any>;
};
export type CloudFile = EntryBase<CloudFileFields> & {
  _name: "cloudFile";
  __fields__: CloudFileFields;
  /**
   * **File Name** (DataField)
   * @type {string}
   * @required true
   */
  $fileName: string;
  /**
   * **File Size** (IntField)
   * @type {number}
   * @required true
   */
  $fileSize: number;
  /**
   * **File Type** (ChoicesField)
   * @type {'audio' | 'image' | 'video' | 'document' | 'application' | 'code' | 'text' | 'font' | 'archive' | 'unknown'}
   * @required true
   */
  $fileType:
    | "audio"
    | "image"
    | "video"
    | "document"
    | "application"
    | "code"
    | "text"
    | "font"
    | "archive"
    | "unknown";
  /**
   * **File Extension** (ChoicesField)
   * @type {'aac' | 'apng' | 'avif' | 'avi' | 'azw' | 'bin' | 'bmp' | 'csh' | 'css' | 'csv' | 'doc' | 'docx' | 'eot' | 'epub' | 'gz' | 'gif' | 'htm' | 'html' | 'ico' | 'ics' | 'jar' | 'jpeg' | 'jpg' | 'js' | 'json' | 'jsonld' | 'mid' | 'midi' | 'mjs' | 'mp3' | 'mp4' | 'mpeg' | 'mpkg' | 'odp' | 'ods' | 'odt' | 'oga' | 'ogv' | 'ogx' | 'opus' | 'otf' | 'png' | 'pdf' | 'php' | 'ppt' | 'pptx' | 'rar' | 'rtf' | 'sh' | 'svg' | 'tar' | 'tif' | 'tiff' | 'ts' | 'ttf' | 'txt' | 'wav' | 'weba' | 'webm' | 'webp' | 'woff' | 'woff2' | 'xhtml' | 'xls' | 'xlsx' | 'xml' | 'zip' | 'arc'}
   */
  $fileExtension?:
    | "aac"
    | "apng"
    | "avif"
    | "avi"
    | "azw"
    | "bin"
    | "bmp"
    | "csh"
    | "css"
    | "csv"
    | "doc"
    | "docx"
    | "eot"
    | "epub"
    | "gz"
    | "gif"
    | "htm"
    | "html"
    | "ico"
    | "ics"
    | "jar"
    | "jpeg"
    | "jpg"
    | "js"
    | "json"
    | "jsonld"
    | "mid"
    | "midi"
    | "mjs"
    | "mp3"
    | "mp4"
    | "mpeg"
    | "mpkg"
    | "odp"
    | "ods"
    | "odt"
    | "oga"
    | "ogv"
    | "ogx"
    | "opus"
    | "otf"
    | "png"
    | "pdf"
    | "php"
    | "ppt"
    | "pptx"
    | "rar"
    | "rtf"
    | "sh"
    | "svg"
    | "tar"
    | "tif"
    | "tiff"
    | "ts"
    | "ttf"
    | "txt"
    | "wav"
    | "weba"
    | "webm"
    | "webp"
    | "woff"
    | "woff2"
    | "xhtml"
    | "xls"
    | "xlsx"
    | "xml"
    | "zip"
    | "arc";
  /**
   * **Mime Type** (DataField)
   * @type {string}
   */
  $mimeType?: string;
  /**
   * **File Type Description** (DataField)
   * @type {string}
   */
  $fileTypeDescription?: string;
  /**
   * **File Path** (TextField)
   * @type {string}
   * @required true
   */
  $filePath: string;
  /**
   * **Public File** (BooleanField)
   * @description If enabled, this file can be accessed publicly without authentication.
   * @type {boolean}
   */
  $publicFile: boolean;
  /**
   * **Optimize Image** (BooleanField)
   * @description If enabled, images will be optimized
   * @type {boolean}
   */
  $optimizeImage: boolean;
  /**
   * **Optimized** (BooleanField)
   * @description Indicates if the image has been optimized.
   * @type {boolean}
   */
  $optimized: boolean;
  /**
   * **Optimize Width** (IntField)
   * @type {number}
   */
  $optimizeWidth?: number;
  /**
   * **Optimize Height** (IntField)
   * @type {number}
   */
  $optimizeHeight?: number;
  /**
   * **Optimize Format** (ChoicesField)
   * @type {'jpeg' | 'png'}
   */
  $optimizeFormat?: "jpeg" | "png";
  /**
   * **Has Thumbnail** (BooleanField)
   * @type {boolean}
   */
  $hasThumbnail: boolean;
  /**
   * **Thumbnail Size** (IntField)
   * @type {number}
   */
  $thumbnailSize?: number;
  /**
   * **Thumbnail Path** (TextField)
   * @type {string}
   */
  $thumbnailPath?: string;
  /**
   * **File** (IDField)
   * @type {string}
   * @required true
   */
  $id: string;
  /**
   * **Created At** (TimeStampField)
   * @description The date and time this entry was created
   * @type {number}
   * @required true
   */
  $createdAt: number;
  /**
   * **Updated At** (TimeStampField)
   * @description The date and time this entry was last updated
   * @type {number}
   * @required true
   */
  $updatedAt: number;
  /**
   * **Tags** (ArrayField)
   * @description Tags associated with this File
   * @type {Array<any>}
   */
  $in__tags?: Array<any>;
  isFieldModified(
    fieldKey: keyof {
      [K in keyof CloudFile as K extends keyof EntryBase ? never : K]: K;
    },
  ): boolean;
};

type GlobalCloudFileFields = {
  /**
   * **File Name** (DataField)
   * @type {string}
   * @required true
   */
  fileName: string;
  /**
   * **File Size** (IntField)
   * @type {number}
   * @required true
   */
  fileSize: number;
  /**
   * **File Type** (ChoicesField)
   * @type {'audio' | 'image' | 'video' | 'document' | 'application' | 'code' | 'text' | 'font' | 'archive' | 'unknown'}
   * @required true
   */
  fileType:
    | "audio"
    | "image"
    | "video"
    | "document"
    | "application"
    | "code"
    | "text"
    | "font"
    | "archive"
    | "unknown";
  /**
   * **File Extension** (ChoicesField)
   * @type {'aac' | 'apng' | 'avif' | 'avi' | 'azw' | 'bin' | 'bmp' | 'csh' | 'css' | 'csv' | 'doc' | 'docx' | 'eot' | 'epub' | 'gz' | 'gif' | 'htm' | 'html' | 'ico' | 'ics' | 'jar' | 'jpeg' | 'jpg' | 'js' | 'json' | 'jsonld' | 'mid' | 'midi' | 'mjs' | 'mp3' | 'mp4' | 'mpeg' | 'mpkg' | 'odp' | 'ods' | 'odt' | 'oga' | 'ogv' | 'ogx' | 'opus' | 'otf' | 'png' | 'pdf' | 'php' | 'ppt' | 'pptx' | 'rar' | 'rtf' | 'sh' | 'svg' | 'tar' | 'tif' | 'tiff' | 'ts' | 'ttf' | 'txt' | 'wav' | 'weba' | 'webm' | 'webp' | 'woff' | 'woff2' | 'xhtml' | 'xls' | 'xlsx' | 'xml' | 'zip' | 'arc'}
   */
  fileExtension?:
    | "aac"
    | "apng"
    | "avif"
    | "avi"
    | "azw"
    | "bin"
    | "bmp"
    | "csh"
    | "css"
    | "csv"
    | "doc"
    | "docx"
    | "eot"
    | "epub"
    | "gz"
    | "gif"
    | "htm"
    | "html"
    | "ico"
    | "ics"
    | "jar"
    | "jpeg"
    | "jpg"
    | "js"
    | "json"
    | "jsonld"
    | "mid"
    | "midi"
    | "mjs"
    | "mp3"
    | "mp4"
    | "mpeg"
    | "mpkg"
    | "odp"
    | "ods"
    | "odt"
    | "oga"
    | "ogv"
    | "ogx"
    | "opus"
    | "otf"
    | "png"
    | "pdf"
    | "php"
    | "ppt"
    | "pptx"
    | "rar"
    | "rtf"
    | "sh"
    | "svg"
    | "tar"
    | "tif"
    | "tiff"
    | "ts"
    | "ttf"
    | "txt"
    | "wav"
    | "weba"
    | "webm"
    | "webp"
    | "woff"
    | "woff2"
    | "xhtml"
    | "xls"
    | "xlsx"
    | "xml"
    | "zip"
    | "arc";
  /**
   * **Mime Type** (DataField)
   * @type {string}
   */
  mimeType?: string;
  /**
   * **File Type Description** (DataField)
   * @type {string}
   */
  fileTypeDescription?: string;
  /**
   * **File Path** (TextField)
   * @type {string}
   * @required true
   */
  filePath: string;
  /**
   * **Public File** (BooleanField)
   * @description If enabled, this file can be accessed publicly without authentication.
   * @type {boolean}
   */
  publicFile: boolean;
  /**
   * **Optimize Image** (BooleanField)
   * @description If enabled, images will be optimized
   * @type {boolean}
   */
  optimizeImage: boolean;
  /**
   * **Optimized** (BooleanField)
   * @description Indicates if the image has been optimized.
   * @type {boolean}
   */
  optimized: boolean;
  /**
   * **Optimize Width** (IntField)
   * @type {number}
   */
  optimizeWidth?: number;
  /**
   * **Optimize Height** (IntField)
   * @type {number}
   */
  optimizeHeight?: number;
  /**
   * **Optimize Format** (ChoicesField)
   * @type {'jpeg' | 'png'}
   */
  optimizeFormat?: "jpeg" | "png";
  /**
   * **Has Thumbnail** (BooleanField)
   * @type {boolean}
   */
  hasThumbnail: boolean;
  /**
   * **Thumbnail Size** (IntField)
   * @type {number}
   */
  thumbnailSize?: number;
  /**
   * **Thumbnail Path** (TextField)
   * @type {string}
   */
  thumbnailPath?: string;
  /**
   * **System File** (IDField)
   * @type {string}
   * @required true
   */
  id: string;
  /**
   * **Created At** (TimeStampField)
   * @description The date and time this entry was created
   * @type {number}
   * @required true
   */
  createdAt: number;
  /**
   * **Updated At** (TimeStampField)
   * @description The date and time this entry was last updated
   * @type {number}
   * @required true
   */
  updatedAt: number;
  /**
   * **Tags** (ArrayField)
   * @description Tags associated with this System File
   * @type {Array<any>}
   */
  in__tags?: Array<any>;
};
export type GlobalCloudFile = EntryBase<GlobalCloudFileFields> & {
  _name: "globalCloudFile";
  __fields__: GlobalCloudFileFields;
  /**
   * **File Name** (DataField)
   * @type {string}
   * @required true
   */
  $fileName: string;
  /**
   * **File Size** (IntField)
   * @type {number}
   * @required true
   */
  $fileSize: number;
  /**
   * **File Type** (ChoicesField)
   * @type {'audio' | 'image' | 'video' | 'document' | 'application' | 'code' | 'text' | 'font' | 'archive' | 'unknown'}
   * @required true
   */
  $fileType:
    | "audio"
    | "image"
    | "video"
    | "document"
    | "application"
    | "code"
    | "text"
    | "font"
    | "archive"
    | "unknown";
  /**
   * **File Extension** (ChoicesField)
   * @type {'aac' | 'apng' | 'avif' | 'avi' | 'azw' | 'bin' | 'bmp' | 'csh' | 'css' | 'csv' | 'doc' | 'docx' | 'eot' | 'epub' | 'gz' | 'gif' | 'htm' | 'html' | 'ico' | 'ics' | 'jar' | 'jpeg' | 'jpg' | 'js' | 'json' | 'jsonld' | 'mid' | 'midi' | 'mjs' | 'mp3' | 'mp4' | 'mpeg' | 'mpkg' | 'odp' | 'ods' | 'odt' | 'oga' | 'ogv' | 'ogx' | 'opus' | 'otf' | 'png' | 'pdf' | 'php' | 'ppt' | 'pptx' | 'rar' | 'rtf' | 'sh' | 'svg' | 'tar' | 'tif' | 'tiff' | 'ts' | 'ttf' | 'txt' | 'wav' | 'weba' | 'webm' | 'webp' | 'woff' | 'woff2' | 'xhtml' | 'xls' | 'xlsx' | 'xml' | 'zip' | 'arc'}
   */
  $fileExtension?:
    | "aac"
    | "apng"
    | "avif"
    | "avi"
    | "azw"
    | "bin"
    | "bmp"
    | "csh"
    | "css"
    | "csv"
    | "doc"
    | "docx"
    | "eot"
    | "epub"
    | "gz"
    | "gif"
    | "htm"
    | "html"
    | "ico"
    | "ics"
    | "jar"
    | "jpeg"
    | "jpg"
    | "js"
    | "json"
    | "jsonld"
    | "mid"
    | "midi"
    | "mjs"
    | "mp3"
    | "mp4"
    | "mpeg"
    | "mpkg"
    | "odp"
    | "ods"
    | "odt"
    | "oga"
    | "ogv"
    | "ogx"
    | "opus"
    | "otf"
    | "png"
    | "pdf"
    | "php"
    | "ppt"
    | "pptx"
    | "rar"
    | "rtf"
    | "sh"
    | "svg"
    | "tar"
    | "tif"
    | "tiff"
    | "ts"
    | "ttf"
    | "txt"
    | "wav"
    | "weba"
    | "webm"
    | "webp"
    | "woff"
    | "woff2"
    | "xhtml"
    | "xls"
    | "xlsx"
    | "xml"
    | "zip"
    | "arc";
  /**
   * **Mime Type** (DataField)
   * @type {string}
   */
  $mimeType?: string;
  /**
   * **File Type Description** (DataField)
   * @type {string}
   */
  $fileTypeDescription?: string;
  /**
   * **File Path** (TextField)
   * @type {string}
   * @required true
   */
  $filePath: string;
  /**
   * **Public File** (BooleanField)
   * @description If enabled, this file can be accessed publicly without authentication.
   * @type {boolean}
   */
  $publicFile: boolean;
  /**
   * **Optimize Image** (BooleanField)
   * @description If enabled, images will be optimized
   * @type {boolean}
   */
  $optimizeImage: boolean;
  /**
   * **Optimized** (BooleanField)
   * @description Indicates if the image has been optimized.
   * @type {boolean}
   */
  $optimized: boolean;
  /**
   * **Optimize Width** (IntField)
   * @type {number}
   */
  $optimizeWidth?: number;
  /**
   * **Optimize Height** (IntField)
   * @type {number}
   */
  $optimizeHeight?: number;
  /**
   * **Optimize Format** (ChoicesField)
   * @type {'jpeg' | 'png'}
   */
  $optimizeFormat?: "jpeg" | "png";
  /**
   * **Has Thumbnail** (BooleanField)
   * @type {boolean}
   */
  $hasThumbnail: boolean;
  /**
   * **Thumbnail Size** (IntField)
   * @type {number}
   */
  $thumbnailSize?: number;
  /**
   * **Thumbnail Path** (TextField)
   * @type {string}
   */
  $thumbnailPath?: string;
  /**
   * **System File** (IDField)
   * @type {string}
   * @required true
   */
  $id: string;
  /**
   * **Created At** (TimeStampField)
   * @description The date and time this entry was created
   * @type {number}
   * @required true
   */
  $createdAt: number;
  /**
   * **Updated At** (TimeStampField)
   * @description The date and time this entry was last updated
   * @type {number}
   * @required true
   */
  $updatedAt: number;
  /**
   * **Tags** (ArrayField)
   * @description Tags associated with this System File
   * @type {Array<any>}
   */
  $in__tags?: Array<any>;
  isFieldModified(
    fieldKey: keyof {
      [K in keyof GlobalCloudFile as K extends keyof EntryBase ? never : K]: K;
    },
  ): boolean;
};

type EmailFields = {
  /**
   * **From** (ConnectionField)
   *
   * **EntryType** `emailAccount`
   * @type {string}
   */
  emailAccount?: string;
  /**
   * **Sender's Name** (DataField)
   * @description The name of the sender
   * @type {string}
   */
  senderName?: string;
  /**
   * **To** (EmailField)
   * @description The email address of the recipient
   * @type {string}
   * @required true
   */
  recipientEmail: string;
  /**
   * **Subject** (TextField)
   * @description The subject of the email
   * @type {string}
   */
  subject?: string;
  /**
   * **Content Type** (ChoicesField)
   * @description The content type of the email
   * @type {'html' | 'text'}
   */
  contentType?: "html" | "text";
  /**
   * **Send Date** (TimeStampField)
   * @description The date the email was sent
   * @type {number}
   */
  sendDate?: number;
  /**
   * **Body** (TextField)
   * @description The body of the email
   * @type {string}
   */
  body?: string;
  /**
   * **HTML Body** (RichTextField)
   * @description The HTML body of the email
   * @type {string}
   */
  htmlBody?: string;
  /**
   * **Link Account** (ConnectionField)
   *
   * **EntryType** `account`
   * @type {string}
   */
  linkAccount?: string;
  /**
   * **Link Entry** (DataField)
   * @type {string}
   */
  linkEntry?: string;
  /**
   * **Link Id** (DataField)
   * @type {string}
   */
  linkId?: string;
  /**
   * **Link Title** (TextField)
   * @description The title of the linked entry
   * @type {string}
   */
  linkTitle?: string;
  /**
   * **Status** (ChoicesField)
   * @description The status of the email
   * @type {'pending' | 'queued' | 'sent' | 'failed'}
   */
  status?: "pending" | "queued" | "sent" | "failed";
  /**
   * **Email** (IDField)
   * @type {string}
   * @required true
   */
  id: string;
  /**
   * **Created At** (TimeStampField)
   * @description The date and time this entry was created
   * @type {number}
   * @required true
   */
  createdAt: number;
  /**
   * **Updated At** (TimeStampField)
   * @description The date and time this entry was last updated
   * @type {number}
   * @required true
   */
  updatedAt: number;
  /**
   * **Tags** (ArrayField)
   * @description Tags associated with this Email
   * @type {Array<any>}
   */
  in__tags?: Array<any>;
  /**
   * **From Title** (EmailField)
   * @description The email account to send emails from
   * @type {string}
   */
  emailAccount__title?: string;
  /**
   * **Link Account Title** (DataField)
   * @description The name of the account
   * @type {string}
   */
  linkAccount__title?: string;
};
export type Email = EntryBase<EmailFields> & {
  _name: "email";
  __fields__: EmailFields;
  /**
   * **From** (ConnectionField)
   *
   * **EntryType** `emailAccount`
   * @type {string}
   */
  $emailAccount?: string;
  /**
   * **Sender's Name** (DataField)
   * @description The name of the sender
   * @type {string}
   */
  $senderName?: string;
  /**
   * **To** (EmailField)
   * @description The email address of the recipient
   * @type {string}
   * @required true
   */
  $recipientEmail: string;
  /**
   * **Subject** (TextField)
   * @description The subject of the email
   * @type {string}
   */
  $subject?: string;
  /**
   * **Content Type** (ChoicesField)
   * @description The content type of the email
   * @type {'html' | 'text'}
   */
  $contentType?: "html" | "text";
  /**
   * **Send Date** (TimeStampField)
   * @description The date the email was sent
   * @type {number}
   */
  $sendDate?: number;
  /**
   * **Body** (TextField)
   * @description The body of the email
   * @type {string}
   */
  $body?: string;
  /**
   * **HTML Body** (RichTextField)
   * @description The HTML body of the email
   * @type {string}
   */
  $htmlBody?: string;
  /**
   * **Link Account** (ConnectionField)
   *
   * **EntryType** `account`
   * @type {string}
   */
  $linkAccount?: string;
  /**
   * **Link Entry** (DataField)
   * @type {string}
   */
  $linkEntry?: string;
  /**
   * **Link Id** (DataField)
   * @type {string}
   */
  $linkId?: string;
  /**
   * **Link Title** (TextField)
   * @description The title of the linked entry
   * @type {string}
   */
  $linkTitle?: string;
  /**
   * **Status** (ChoicesField)
   * @description The status of the email
   * @type {'pending' | 'queued' | 'sent' | 'failed'}
   */
  $status?: "pending" | "queued" | "sent" | "failed";
  /**
   * **Email** (IDField)
   * @type {string}
   * @required true
   */
  $id: string;
  /**
   * **Created At** (TimeStampField)
   * @description The date and time this entry was created
   * @type {number}
   * @required true
   */
  $createdAt: number;
  /**
   * **Updated At** (TimeStampField)
   * @description The date and time this entry was last updated
   * @type {number}
   * @required true
   */
  $updatedAt: number;
  /**
   * **Tags** (ArrayField)
   * @description Tags associated with this Email
   * @type {Array<any>}
   */
  $in__tags?: Array<any>;
  /**
   * **From Title** (EmailField)
   * @description The email account to send emails from
   * @type {string}
   */
  $emailAccount__title?: string;
  /**
   * **Link Account Title** (DataField)
   * @description The name of the account
   * @type {string}
   */
  $linkAccount__title?: string;
  isFieldModified(
    fieldKey: keyof {
      [K in keyof Email as K extends keyof EntryBase ? never : K]: K;
    },
  ): boolean;
  runAction<N extends keyof EmailActionMap>(
    actionName: N,
  ): EmailActionMap[N]["return"];
};
type EmailActionMap = {
  enqueueSend: {
    return: Promise<any>;
  };
  send: {
    return: Promise<any>;
  };
};

type EmailAccountFields = {
  /**
   * **Email Account** (EmailField)
   * @description The email account to send emails from
   * @type {string}
   * @required true
   */
  emailAccount: string;
  /**
   * **Sender's Name** (DataField)
   * @description The name to use when sending emails
   * @type {string}
   */
  senderName?: string;
  /**
   * **Use Gmail OAuth** (BooleanField)
   * @description Use OAuth to authenticate with Gmail
   * @type {boolean}
   */
  useGmailOauth: boolean;
  /**
   * **Authorize Gmail** (URLField)
   * @description The URL to authorize this email account with Gmail
   * @type {string}
   */
  authUrl?: string;
  /**
   * **Send Emails** (BooleanField)
   * @description Whether this email account can send emails
   * @type {boolean}
   */
  sendEmails: boolean;
  /**
   * **Receive Emails** (BooleanField)
   * @description Whether this email account can receive emails
   * @type {boolean}
   */
  receiveEmails: boolean;
  /**
   * **SMTP Host** (TextField)
   * @description The host of the SMTP server. smtp.gmail.com for Gmail
   * @type {string}
   */
  smtpHost?: string;
  /**
   * **SMTP Port** (IntField)
   * @description The port of the SMTP server. 587 for Gmail
   * @type {number}
   */
  smtpPort?: number;
  /**
   * **SMTP User** (DataField)
   * @description The user to authenticate with the SMTP server. This is usually the email address
   * @type {string}
   */
  smtpUser?: string;
  /**
   * **SMTP Password** (PasswordField)
   * @description The password to authenticate with the SMTP server. Not required if using Gmail OAuth
   * @type {string}
   */
  smtpPassword?: string;
  /**
   * **Auth Status** (ChoicesField)
   * @type {'unauthorized' | 'authorized'}
   */
  authStatus?: "unauthorized" | "authorized";
  /**
   * **Access Token** (TextField)
   * @type {string}
   */
  accessToken?: string;
  /**
   * **Expire Time** (TimeStampField)
   * @type {number}
   */
  expireTime?: number;
  /**
   * **Acquired Time** (TimeStampField)
   * @type {number}
   */
  acquiredTime?: number;
  /**
   * **Refresh Token** (TextField)
   * @type {string}
   */
  refreshToken?: string;
  /**
   * **Token Type** (DataField)
   * @type {string}
   */
  tokenType?: string;
  /**
   * **Email Account** (IDField)
   * @type {string}
   * @required true
   */
  id: string;
  /**
   * **Created At** (TimeStampField)
   * @description The date and time this entry was created
   * @type {number}
   * @required true
   */
  createdAt: number;
  /**
   * **Updated At** (TimeStampField)
   * @description The date and time this entry was last updated
   * @type {number}
   * @required true
   */
  updatedAt: number;
  /**
   * **Tags** (ArrayField)
   * @description Tags associated with this Email Account
   * @type {Array<any>}
   */
  in__tags?: Array<any>;
};
export type EmailAccount = EntryBase<EmailAccountFields> & {
  _name: "emailAccount";
  __fields__: EmailAccountFields;
  /**
   * **Email Account** (EmailField)
   * @description The email account to send emails from
   * @type {string}
   * @required true
   */
  $emailAccount: string;
  /**
   * **Sender's Name** (DataField)
   * @description The name to use when sending emails
   * @type {string}
   */
  $senderName?: string;
  /**
   * **Use Gmail OAuth** (BooleanField)
   * @description Use OAuth to authenticate with Gmail
   * @type {boolean}
   */
  $useGmailOauth: boolean;
  /**
   * **Authorize Gmail** (URLField)
   * @description The URL to authorize this email account with Gmail
   * @type {string}
   */
  $authUrl?: string;
  /**
   * **Send Emails** (BooleanField)
   * @description Whether this email account can send emails
   * @type {boolean}
   */
  $sendEmails: boolean;
  /**
   * **Receive Emails** (BooleanField)
   * @description Whether this email account can receive emails
   * @type {boolean}
   */
  $receiveEmails: boolean;
  /**
   * **SMTP Host** (TextField)
   * @description The host of the SMTP server. smtp.gmail.com for Gmail
   * @type {string}
   */
  $smtpHost?: string;
  /**
   * **SMTP Port** (IntField)
   * @description The port of the SMTP server. 587 for Gmail
   * @type {number}
   */
  $smtpPort?: number;
  /**
   * **SMTP User** (DataField)
   * @description The user to authenticate with the SMTP server. This is usually the email address
   * @type {string}
   */
  $smtpUser?: string;
  /**
   * **SMTP Password** (PasswordField)
   * @description The password to authenticate with the SMTP server. Not required if using Gmail OAuth
   * @type {string}
   */
  $smtpPassword?: string;
  /**
   * **Auth Status** (ChoicesField)
   * @type {'unauthorized' | 'authorized'}
   */
  $authStatus?: "unauthorized" | "authorized";
  /**
   * **Access Token** (TextField)
   * @type {string}
   */
  $accessToken?: string;
  /**
   * **Expire Time** (TimeStampField)
   * @type {number}
   */
  $expireTime?: number;
  /**
   * **Acquired Time** (TimeStampField)
   * @type {number}
   */
  $acquiredTime?: number;
  /**
   * **Refresh Token** (TextField)
   * @type {string}
   */
  $refreshToken?: string;
  /**
   * **Token Type** (DataField)
   * @type {string}
   */
  $tokenType?: string;
  /**
   * **Email Account** (IDField)
   * @type {string}
   * @required true
   */
  $id: string;
  /**
   * **Created At** (TimeStampField)
   * @description The date and time this entry was created
   * @type {number}
   * @required true
   */
  $createdAt: number;
  /**
   * **Updated At** (TimeStampField)
   * @description The date and time this entry was last updated
   * @type {number}
   * @required true
   */
  $updatedAt: number;
  /**
   * **Tags** (ArrayField)
   * @description Tags associated with this Email Account
   * @type {Array<any>}
   */
  $in__tags?: Array<any>;
  isFieldModified(
    fieldKey: keyof {
      [K in keyof EmailAccount as K extends keyof EntryBase ? never : K]: K;
    },
  ): boolean;
  runAction<N extends keyof EmailAccountActionMap>(
    actionName: N,
  ): EmailAccountActionMap[N]["return"];
};
type EmailAccountActionMap = {
  refreshToken: {
    return: Promise<any>;
  };
};

type EmailTemplateFields = {
  /**
   * **Title** (DataField)
   * @type {string}
   * @required true
   */
  title: string;
  /**
   * **Subject** (DataField)
   * @type {string}
   */
  subject?: string;
  /**
   * **Content** (RichTextField)
   * @type {string}
   */
  content?: string;
  /**
   * **ID** (IDField)
   * @type {string}
   * @required true
   */
  id: string;
  /**
   * **Created At** (TimeStampField)
   * @description The date and time this entry was created
   * @type {number}
   * @required true
   */
  createdAt: number;
  /**
   * **Updated At** (TimeStampField)
   * @description The date and time this entry was last updated
   * @type {number}
   * @required true
   */
  updatedAt: number;
  /**
   * **Tags** (ArrayField)
   * @description Tags associated with this Email Template
   * @type {Array<any>}
   */
  in__tags?: Array<any>;
};
export type EmailTemplate = EntryBase<EmailTemplateFields> & {
  _name: "emailTemplate";
  __fields__: EmailTemplateFields;
  /**
   * **Title** (DataField)
   * @type {string}
   * @required true
   */
  $title: string;
  /**
   * **Subject** (DataField)
   * @type {string}
   */
  $subject?: string;
  /**
   * **Content** (RichTextField)
   * @type {string}
   */
  $content?: string;
  /**
   * **ID** (IDField)
   * @type {string}
   * @required true
   */
  $id: string;
  /**
   * **Created At** (TimeStampField)
   * @description The date and time this entry was created
   * @type {number}
   * @required true
   */
  $createdAt: number;
  /**
   * **Updated At** (TimeStampField)
   * @description The date and time this entry was last updated
   * @type {number}
   * @required true
   */
  $updatedAt: number;
  /**
   * **Tags** (ArrayField)
   * @description Tags associated with this Email Template
   * @type {Array<any>}
   */
  $in__tags?: Array<any>;
  isFieldModified(
    fieldKey: keyof {
      [K in keyof EmailTemplate as K extends keyof EntryBase ? never : K]: K;
    },
  ): boolean;
  runAction<N extends keyof EmailTemplateParamsActionMap>(
    actionName: N,
    params: EmailTemplateParamsActionMap[N]["params"],
  ): EmailTemplateParamsActionMap[N]["return"];
};
type EmailTemplateParamsActionMap = {
  renderTemplate: {
    params: {
      /**
       * **Params** (JSONField)
       * @type {Record<string, any>}
       * @required true
       */
      params: Record<string, any>;
    };
    return: any;
  };
};

type OnboardingStepFields = {
  /**
   * **Title** (DataField)
   * @type {string}
   * @required true
   */
  title: string;
  /**
   * **Description** (TextField)
   * @type {string}
   */
  description?: string;
  /**
   * **Order** (IntField)
   * @type {number}
   * @required true
   */
  order: number;
  /**
   * **ID** (IDField)
   * @type {string}
   * @required true
   */
  id: string;
  /**
   * **Created At** (TimeStampField)
   * @description The date and time this entry was created
   * @type {number}
   * @required true
   */
  createdAt: number;
  /**
   * **Updated At** (TimeStampField)
   * @description The date and time this entry was last updated
   * @type {number}
   * @required true
   */
  updatedAt: number;
  /**
   * **Tags** (ArrayField)
   * @description Tags associated with this Onboarding Step
   * @type {Array<any>}
   */
  in__tags?: Array<any>;
  onboardingField: ChildList<{
    /**
     * **Key** (DataField)
     * @description The unique identifier for the field, used in forms and data processing.
     * @type {string}
     * @required true
     */
    key: string;
    /**
     * **Label** (DataField)
     * @description The label for the field, displayed to the user.
     * @type {string}
     */
    label?: string;
    /**
     * **Placeholder** (DataField)
     * @description Placeholder text for the field, providing a hint to the user about what to enter.
     * @type {string}
     */
    placeholder?: string;
    /**
     * **Required** (BooleanField)
     * @description Indicates whether the field is required to be filled out by the user.
     * @type {boolean}
     */
    required: boolean;
    /**
     * **Description** (TextField)
     * @description A short description of the field, explaining its purpose and usage. This will be displayed to the user under the field input.
     * @type {string}
     */
    description?: string;
    /**
     * **Type** (ChoicesField)
     * @type {'DataField' | 'TextField' | 'EmailField' | 'PasswordField' | 'PhoneField' | 'URLField' | 'DateField' | 'TimeField' | 'TimeStampField' | 'BooleanField' | 'ChoicesField' | 'MultiChoiceField' | 'ListField' | 'JSONField' | 'ImageField' | 'FileField' | 'CurrencyField'}
     * @required true
     */
    type:
      | "DataField"
      | "TextField"
      | "EmailField"
      | "PasswordField"
      | "PhoneField"
      | "URLField"
      | "DateField"
      | "TimeField"
      | "TimeStampField"
      | "BooleanField"
      | "ChoicesField"
      | "MultiChoiceField"
      | "ListField"
      | "JSONField"
      | "ImageField"
      | "FileField"
      | "CurrencyField";
    /**
     * **Choices** (JSONField)
     * @type {Record<string, any>}
     */
    choices?: Record<string, any>;
    /**
     * **ID** (IDField)
     * @type {string}
     * @required true
     */
    id: string;
    /**
     * **Order** (IntField)
     * @description The order of this child in the list
     * @type {number}
     */
    order?: number;
    /**
     * **Created At** (TimeStampField)
     * @description The date and time this child was created
     * @type {number}
     * @required true
     */
    createdAt: number;
    /**
     * **Updated At** (TimeStampField)
     * @description The date and time this child was last updated
     * @type {number}
     * @required true
     */
    updatedAt: number;
    /**
     * **Parent** (ConnectionField)
     *
     * **EntryType** `onboardingStep`
     * @type {string}
     * @required true
     */
    parent: string;
    /**
     * **Parent Title** (DataField)
     * @type {string}
     */
    parent__title?: string;
  }>;
};
export type OnboardingStep = EntryBase<OnboardingStepFields> & {
  _name: "onboardingStep";
  __fields__: OnboardingStepFields;
  /**
   * **Title** (DataField)
   * @type {string}
   * @required true
   */
  $title: string;
  /**
   * **Description** (TextField)
   * @type {string}
   */
  $description?: string;
  /**
   * **Order** (IntField)
   * @type {number}
   * @required true
   */
  $order: number;
  /**
   * **ID** (IDField)
   * @type {string}
   * @required true
   */
  $id: string;
  /**
   * **Created At** (TimeStampField)
   * @description The date and time this entry was created
   * @type {number}
   * @required true
   */
  $createdAt: number;
  /**
   * **Updated At** (TimeStampField)
   * @description The date and time this entry was last updated
   * @type {number}
   * @required true
   */
  $updatedAt: number;
  /**
   * **Tags** (ArrayField)
   * @description Tags associated with this Onboarding Step
   * @type {Array<any>}
   */
  $in__tags?: Array<any>;
  isFieldModified(
    fieldKey: keyof {
      [K in keyof OnboardingStep as K extends keyof EntryBase ? never : K]: K;
    },
  ): boolean;
  $onboardingField: ChildList<{
    /**
     * **Key** (DataField)
     * @description The unique identifier for the field, used in forms and data processing.
     * @type {string}
     * @required true
     */
    key: string;
    /**
     * **Label** (DataField)
     * @description The label for the field, displayed to the user.
     * @type {string}
     */
    label?: string;
    /**
     * **Placeholder** (DataField)
     * @description Placeholder text for the field, providing a hint to the user about what to enter.
     * @type {string}
     */
    placeholder?: string;
    /**
     * **Required** (BooleanField)
     * @description Indicates whether the field is required to be filled out by the user.
     * @type {boolean}
     */
    required: boolean;
    /**
     * **Description** (TextField)
     * @description A short description of the field, explaining its purpose and usage. This will be displayed to the user under the field input.
     * @type {string}
     */
    description?: string;
    /**
     * **Type** (ChoicesField)
     * @type {'DataField' | 'TextField' | 'EmailField' | 'PasswordField' | 'PhoneField' | 'URLField' | 'DateField' | 'TimeField' | 'TimeStampField' | 'BooleanField' | 'ChoicesField' | 'MultiChoiceField' | 'ListField' | 'JSONField' | 'ImageField' | 'FileField' | 'CurrencyField'}
     * @required true
     */
    type:
      | "DataField"
      | "TextField"
      | "EmailField"
      | "PasswordField"
      | "PhoneField"
      | "URLField"
      | "DateField"
      | "TimeField"
      | "TimeStampField"
      | "BooleanField"
      | "ChoicesField"
      | "MultiChoiceField"
      | "ListField"
      | "JSONField"
      | "ImageField"
      | "FileField"
      | "CurrencyField";
    /**
     * **Choices** (JSONField)
     * @type {Record<string, any>}
     */
    choices?: Record<string, any>;
    /**
     * **ID** (IDField)
     * @type {string}
     * @required true
     */
    id: string;
    /**
     * **Order** (IntField)
     * @description The order of this child in the list
     * @type {number}
     */
    order?: number;
    /**
     * **Created At** (TimeStampField)
     * @description The date and time this child was created
     * @type {number}
     * @required true
     */
    createdAt: number;
    /**
     * **Updated At** (TimeStampField)
     * @description The date and time this child was last updated
     * @type {number}
     * @required true
     */
    updatedAt: number;
    /**
     * **Parent** (ConnectionField)
     *
     * **EntryType** `onboardingStep`
     * @type {string}
     * @required true
     */
    parent: string;
    /**
     * **Parent Title** (DataField)
     * @type {string}
     */
    parent__title?: string;
  }>;
};

type UserRoleFields = {
  /**
   * **Role Key** (DataField)
   * @type {string}
   * @required true
   */
  roleKey: string;
  /**
   * **Role Name** (DataField)
   * @type {string}
   * @required true
   */
  roleName: string;
  /**
   * **Description** (TextField)
   * @description A short description of the role
   * @type {string}
   */
  description?: string;
  /**
   * **ID** (IDField)
   * @type {string}
   * @required true
   */
  id: string;
  /**
   * **Created At** (TimeStampField)
   * @description The date and time this entry was created
   * @type {number}
   * @required true
   */
  createdAt: number;
  /**
   * **Updated At** (TimeStampField)
   * @description The date and time this entry was last updated
   * @type {number}
   * @required true
   */
  updatedAt: number;
  /**
   * **Tags** (ArrayField)
   * @description Tags associated with this User Role
   * @type {Array<any>}
   */
  in__tags?: Array<any>;
};
export type UserRole = EntryBase<UserRoleFields> & {
  _name: "userRole";
  __fields__: UserRoleFields;
  /**
   * **Role Key** (DataField)
   * @type {string}
   * @required true
   */
  $roleKey: string;
  /**
   * **Role Name** (DataField)
   * @type {string}
   * @required true
   */
  $roleName: string;
  /**
   * **Description** (TextField)
   * @description A short description of the role
   * @type {string}
   */
  $description?: string;
  /**
   * **ID** (IDField)
   * @type {string}
   * @required true
   */
  $id: string;
  /**
   * **Created At** (TimeStampField)
   * @description The date and time this entry was created
   * @type {number}
   * @required true
   */
  $createdAt: number;
  /**
   * **Updated At** (TimeStampField)
   * @description The date and time this entry was last updated
   * @type {number}
   * @required true
   */
  $updatedAt: number;
  /**
   * **Tags** (ArrayField)
   * @description Tags associated with this User Role
   * @type {Array<any>}
   */
  $in__tags?: Array<any>;
  isFieldModified(
    fieldKey: keyof {
      [K in keyof UserRole as K extends keyof EntryBase ? never : K]: K;
    },
  ): boolean;
  runAction<N extends keyof UserRoleActionMap>(
    actionName: N,
  ): UserRoleActionMap[N]["return"];
};
type UserRoleActionMap = {
  generateConfig: {
    return: Promise<any>;
  };
};

type EntryMetaFields = {
  /**
   * **Name** (DataField)
   * @description The unique name of this entry type
   * @type {string}
   * @required true
   */
  name: string;
  /**
   * **Label** (DataField)
   * @type {string}
   * @required true
   */
  label: string;
  /**
   * **Description** (TextField)
   * @type {string}
   */
  description?: string;
  /**
   * **Extension** (ConnectionField)
   *
   * **EntryType** `extensionMeta`
   * @description The extension this entry type belongs to
   * @type {string}
   */
  extension?: string;
  /**
   * **Title Field** (DataField)
   * @description The field to use as the title when displaying this entry type
   * @type {string}
   */
  titleField?: string;
  /**
   * **System Global** (BooleanField)
   * @type {boolean}
   */
  systemGlobal: boolean;
  /**
   * **ID** (IDField)
   * @type {string}
   * @required true
   */
  id: string;
  /**
   * **Created At** (TimeStampField)
   * @description The date and time this entry was created
   * @type {number}
   * @required true
   */
  createdAt: number;
  /**
   * **Updated At** (TimeStampField)
   * @description The date and time this entry was last updated
   * @type {number}
   * @required true
   */
  updatedAt: number;
  /**
   * **Tags** (ArrayField)
   * @description Tags associated with this Entry Meta
   * @type {Array<any>}
   */
  in__tags?: Array<any>;
  /**
   * **Extension Title** (DataField)
   * @type {string}
   */
  extension__title?: string;
};
export type EntryMeta = EntryBase<EntryMetaFields> & {
  _name: "entryMeta";
  __fields__: EntryMetaFields;
  /**
   * **Name** (DataField)
   * @description The unique name of this entry type
   * @type {string}
   * @required true
   */
  $name: string;
  /**
   * **Label** (DataField)
   * @type {string}
   * @required true
   */
  $label: string;
  /**
   * **Description** (TextField)
   * @type {string}
   */
  $description?: string;
  /**
   * **Extension** (ConnectionField)
   *
   * **EntryType** `extensionMeta`
   * @description The extension this entry type belongs to
   * @type {string}
   */
  $extension?: string;
  /**
   * **Title Field** (DataField)
   * @description The field to use as the title when displaying this entry type
   * @type {string}
   */
  $titleField?: string;
  /**
   * **System Global** (BooleanField)
   * @type {boolean}
   */
  $systemGlobal: boolean;
  /**
   * **ID** (IDField)
   * @type {string}
   * @required true
   */
  $id: string;
  /**
   * **Created At** (TimeStampField)
   * @description The date and time this entry was created
   * @type {number}
   * @required true
   */
  $createdAt: number;
  /**
   * **Updated At** (TimeStampField)
   * @description The date and time this entry was last updated
   * @type {number}
   * @required true
   */
  $updatedAt: number;
  /**
   * **Tags** (ArrayField)
   * @description Tags associated with this Entry Meta
   * @type {Array<any>}
   */
  $in__tags?: Array<any>;
  /**
   * **Extension Title** (DataField)
   * @type {string}
   */
  $extension__title?: string;
  isFieldModified(
    fieldKey: keyof {
      [K in keyof EntryMeta as K extends keyof EntryBase ? never : K]: K;
    },
  ): boolean;
};

type ExtensionMetaFields = {
  /**
   * **Key** (DataField)
   * @type {string}
   * @required true
   */
  key: string;
  /**
   * **Label** (DataField)
   * @type {string}
   * @required true
   */
  label: string;
  /**
   * **Description** (TextField)
   * @type {string}
   */
  description?: string;
  /**
   * **Version** (DataField)
   * @description The version of this extension
   * @type {string}
   */
  version?: string;
  /**
   * **Cloud Extension** (IDField)
   * @type {string}
   * @required true
   */
  id: string;
  /**
   * **Created At** (TimeStampField)
   * @description The date and time this entry was created
   * @type {number}
   * @required true
   */
  createdAt: number;
  /**
   * **Updated At** (TimeStampField)
   * @description The date and time this entry was last updated
   * @type {number}
   * @required true
   */
  updatedAt: number;
  /**
   * **Tags** (ArrayField)
   * @description Tags associated with this Cloud Extension
   * @type {Array<any>}
   */
  in__tags?: Array<any>;
};
export type ExtensionMeta = EntryBase<ExtensionMetaFields> & {
  _name: "extensionMeta";
  __fields__: ExtensionMetaFields;
  /**
   * **Key** (DataField)
   * @type {string}
   * @required true
   */
  $key: string;
  /**
   * **Label** (DataField)
   * @type {string}
   * @required true
   */
  $label: string;
  /**
   * **Description** (TextField)
   * @type {string}
   */
  $description?: string;
  /**
   * **Version** (DataField)
   * @description The version of this extension
   * @type {string}
   */
  $version?: string;
  /**
   * **Cloud Extension** (IDField)
   * @type {string}
   * @required true
   */
  $id: string;
  /**
   * **Created At** (TimeStampField)
   * @description The date and time this entry was created
   * @type {number}
   * @required true
   */
  $createdAt: number;
  /**
   * **Updated At** (TimeStampField)
   * @description The date and time this entry was last updated
   * @type {number}
   * @required true
   */
  $updatedAt: number;
  /**
   * **Tags** (ArrayField)
   * @description Tags associated with this Cloud Extension
   * @type {Array<any>}
   */
  $in__tags?: Array<any>;
  isFieldModified(
    fieldKey: keyof {
      [K in keyof ExtensionMeta as K extends keyof EntryBase ? never : K]: K;
    },
  ): boolean;
};

type FieldMetaFields = {
  /**
   * **Entry Meta** (ConnectionField)
   *
   * **EntryType** `entryMeta`
   * @type {string}
   * @required true
   */
  entryMeta: string;
  /**
   * **Key** (DataField)
   * @type {string}
   * @required true
   */
  key: string;
  /**
   * **Label** (DataField)
   * @type {string}
   * @required true
   */
  label: string;
  /**
   * **Type** (ChoicesField)
   * @type {'BigIntField' | 'BooleanField' | 'ChoicesField' | 'ConnectionField' | 'CurrencyField' | 'DataField' | 'DateField' | 'DecimalField' | 'EmailField' | 'ImageField' | 'IntField' | 'JSONField' | 'ListField' | 'MultiChoiceField' | 'PasswordField' | 'PhoneField' | 'RichTextField' | 'TextField' | 'TimeStampField' | 'URLField' | 'IDField' | 'FileField' | 'TimeField' | 'CodeField' | 'ArrayField'}
   * @required true
   */
  type:
    | "BigIntField"
    | "BooleanField"
    | "ChoicesField"
    | "ConnectionField"
    | "CurrencyField"
    | "DataField"
    | "DateField"
    | "DecimalField"
    | "EmailField"
    | "ImageField"
    | "IntField"
    | "JSONField"
    | "ListField"
    | "MultiChoiceField"
    | "PasswordField"
    | "PhoneField"
    | "RichTextField"
    | "TextField"
    | "TimeStampField"
    | "URLField"
    | "IDField"
    | "FileField"
    | "TimeField"
    | "CodeField"
    | "ArrayField";
  /**
   * **Description** (TextField)
   * @description A brief description of the field.
   * @type {string}
   */
  description?: string;
  /**
   * **Required** (BooleanField)
   * @description Whether the field is mandatory.
   * @type {boolean}
   */
  required: boolean;
  /**
   * **Read Only** (BooleanField)
   * @description Whether the field is read-only.
   * @type {boolean}
   */
  readOnly: boolean;
  /**
   * **Unique** (BooleanField)
   * @description Whether the field must have unique values across entries.
   * @type {boolean}
   */
  unique: boolean;
  /**
   * **Default Value** (DataField)
   * @description The default value for the field.
   * @type {string}
   */
  defaultValue?: string;
  /**
   * **Hidden** (BooleanField)
   * @description Whether the field is hidden in the UI.
   * @type {boolean}
   */
  hidden: boolean;
  /**
   * **Placeholder** (DataField)
   * @description Placeholder text for the field.
   * @type {string}
   */
  placeholder?: string;
  /**
   * **Entry Type** (ConnectionField)
   *
   * **EntryType** `entryMeta`
   * @description The entry type this connection field is associated with.
   * @type {string}
   */
  entryType?: string;
  /**
   * **Field Meta** (IDField)
   * @type {string}
   * @required true
   */
  id: string;
  /**
   * **Created At** (TimeStampField)
   * @description The date and time this entry was created
   * @type {number}
   * @required true
   */
  createdAt: number;
  /**
   * **Updated At** (TimeStampField)
   * @description The date and time this entry was last updated
   * @type {number}
   * @required true
   */
  updatedAt: number;
  /**
   * **Tags** (ArrayField)
   * @description Tags associated with this Field Meta
   * @type {Array<any>}
   */
  in__tags?: Array<any>;
  /**
   * **Entry Meta Title** (DataField)
   * @type {string}
   */
  entryMeta__title?: string;
  /**
   * **Entry Type Title** (DataField)
   * @type {string}
   */
  entryType__title?: string;
};
export type FieldMeta = EntryBase<FieldMetaFields> & {
  _name: "fieldMeta";
  __fields__: FieldMetaFields;
  /**
   * **Entry Meta** (ConnectionField)
   *
   * **EntryType** `entryMeta`
   * @type {string}
   * @required true
   */
  $entryMeta: string;
  /**
   * **Key** (DataField)
   * @type {string}
   * @required true
   */
  $key: string;
  /**
   * **Label** (DataField)
   * @type {string}
   * @required true
   */
  $label: string;
  /**
   * **Type** (ChoicesField)
   * @type {'BigIntField' | 'BooleanField' | 'ChoicesField' | 'ConnectionField' | 'CurrencyField' | 'DataField' | 'DateField' | 'DecimalField' | 'EmailField' | 'ImageField' | 'IntField' | 'JSONField' | 'ListField' | 'MultiChoiceField' | 'PasswordField' | 'PhoneField' | 'RichTextField' | 'TextField' | 'TimeStampField' | 'URLField' | 'IDField' | 'FileField' | 'TimeField' | 'CodeField' | 'ArrayField'}
   * @required true
   */
  $type:
    | "BigIntField"
    | "BooleanField"
    | "ChoicesField"
    | "ConnectionField"
    | "CurrencyField"
    | "DataField"
    | "DateField"
    | "DecimalField"
    | "EmailField"
    | "ImageField"
    | "IntField"
    | "JSONField"
    | "ListField"
    | "MultiChoiceField"
    | "PasswordField"
    | "PhoneField"
    | "RichTextField"
    | "TextField"
    | "TimeStampField"
    | "URLField"
    | "IDField"
    | "FileField"
    | "TimeField"
    | "CodeField"
    | "ArrayField";
  /**
   * **Description** (TextField)
   * @description A brief description of the field.
   * @type {string}
   */
  $description?: string;
  /**
   * **Required** (BooleanField)
   * @description Whether the field is mandatory.
   * @type {boolean}
   */
  $required: boolean;
  /**
   * **Read Only** (BooleanField)
   * @description Whether the field is read-only.
   * @type {boolean}
   */
  $readOnly: boolean;
  /**
   * **Unique** (BooleanField)
   * @description Whether the field must have unique values across entries.
   * @type {boolean}
   */
  $unique: boolean;
  /**
   * **Default Value** (DataField)
   * @description The default value for the field.
   * @type {string}
   */
  $defaultValue?: string;
  /**
   * **Hidden** (BooleanField)
   * @description Whether the field is hidden in the UI.
   * @type {boolean}
   */
  $hidden: boolean;
  /**
   * **Placeholder** (DataField)
   * @description Placeholder text for the field.
   * @type {string}
   */
  $placeholder?: string;
  /**
   * **Entry Type** (ConnectionField)
   *
   * **EntryType** `entryMeta`
   * @description The entry type this connection field is associated with.
   * @type {string}
   */
  $entryType?: string;
  /**
   * **Field Meta** (IDField)
   * @type {string}
   * @required true
   */
  $id: string;
  /**
   * **Created At** (TimeStampField)
   * @description The date and time this entry was created
   * @type {number}
   * @required true
   */
  $createdAt: number;
  /**
   * **Updated At** (TimeStampField)
   * @description The date and time this entry was last updated
   * @type {number}
   * @required true
   */
  $updatedAt: number;
  /**
   * **Tags** (ArrayField)
   * @description Tags associated with this Field Meta
   * @type {Array<any>}
   */
  $in__tags?: Array<any>;
  /**
   * **Entry Meta Title** (DataField)
   * @type {string}
   */
  $entryMeta__title?: string;
  /**
   * **Entry Type Title** (DataField)
   * @type {string}
   */
  $entryType__title?: string;
  isFieldModified(
    fieldKey: keyof {
      [K in keyof FieldMeta as K extends keyof EntryBase ? never : K]: K;
    },
  ): boolean;
};

type EntryActionFields = {
  /**
   * **Key** (DataField)
   * @type {string}
   * @required true
   */
  key: string;
  /**
   * **Label** (DataField)
   * @type {string}
   * @required true
   */
  label: string;
  /**
   * **Entry Meta** (ConnectionField)
   *
   * **EntryType** `entryMeta`
   * @type {string}
   * @required true
   */
  entryMeta: string;
  /**
   * **ID** (IDField)
   * @type {string}
   * @required true
   */
  id: string;
  /**
   * **Created At** (TimeStampField)
   * @description The date and time this entry was created
   * @type {number}
   * @required true
   */
  createdAt: number;
  /**
   * **Updated At** (TimeStampField)
   * @description The date and time this entry was last updated
   * @type {number}
   * @required true
   */
  updatedAt: number;
  /**
   * **Tags** (ArrayField)
   * @description Tags associated with this Entry Action
   * @type {Array<any>}
   */
  in__tags?: Array<any>;
  /**
   * **Entry Meta Title** (DataField)
   * @type {string}
   */
  entryMeta__title?: string;
};
export type EntryAction = EntryBase<EntryActionFields> & {
  _name: "entryAction";
  __fields__: EntryActionFields;
  /**
   * **Key** (DataField)
   * @type {string}
   * @required true
   */
  $key: string;
  /**
   * **Label** (DataField)
   * @type {string}
   * @required true
   */
  $label: string;
  /**
   * **Entry Meta** (ConnectionField)
   *
   * **EntryType** `entryMeta`
   * @type {string}
   * @required true
   */
  $entryMeta: string;
  /**
   * **ID** (IDField)
   * @type {string}
   * @required true
   */
  $id: string;
  /**
   * **Created At** (TimeStampField)
   * @description The date and time this entry was created
   * @type {number}
   * @required true
   */
  $createdAt: number;
  /**
   * **Updated At** (TimeStampField)
   * @description The date and time this entry was last updated
   * @type {number}
   * @required true
   */
  $updatedAt: number;
  /**
   * **Tags** (ArrayField)
   * @description Tags associated with this Entry Action
   * @type {Array<any>}
   */
  $in__tags?: Array<any>;
  /**
   * **Entry Meta Title** (DataField)
   * @type {string}
   */
  $entryMeta__title?: string;
  isFieldModified(
    fieldKey: keyof {
      [K in keyof EntryAction as K extends keyof EntryBase ? never : K]: K;
    },
  ): boolean;
};

type EntryPermissionFields = {
  /**
   * **Role** (ConnectionField)
   *
   * **EntryType** `userRole`
   * @description The user role this permission applies to
   * @type {string}
   * @required true
   */
  role: string;
  /**
   * **Entry** (ConnectionField)
   *
   * **EntryType** `entryMeta`
   * @description The entry type this permission applies to
   * @type {string}
   * @required true
   */
  entryMeta: string;
  /**
   * **Can View** (BooleanField)
   * @type {boolean}
   */
  canView: boolean;
  /**
   * **Can Modify** (BooleanField)
   * @type {boolean}
   */
  canModify: boolean;
  /**
   * **Can Create** (BooleanField)
   * @type {boolean}
   */
  canCreate: boolean;
  /**
   * **Can Delete** (BooleanField)
   * @type {boolean}
   */
  canDelete: boolean;
  /**
   * **ID** (IDField)
   * @type {string}
   * @required true
   */
  id: string;
  /**
   * **Created At** (TimeStampField)
   * @description The date and time this entry was created
   * @type {number}
   * @required true
   */
  createdAt: number;
  /**
   * **Updated At** (TimeStampField)
   * @description The date and time this entry was last updated
   * @type {number}
   * @required true
   */
  updatedAt: number;
  /**
   * **Tags** (ArrayField)
   * @description Tags associated with this Entry Permission
   * @type {Array<any>}
   */
  in__tags?: Array<any>;
  /**
   * **Role Title** (DataField)
   * @type {string}
   */
  role__title?: string;
  /**
   * **Entry Title** (DataField)
   * @type {string}
   */
  entryMeta__title?: string;
  fieldPermissions: ChildList<{
    /**
     * **Field** (ConnectionField)
     *
     * **EntryType** `fieldMeta`
     * @type {string}
     * @required true
     */
    field: string;
    /**
     * **Can View** (BooleanField)
     * @type {boolean}
     */
    canView: boolean;
    /**
     * **Can Modify** (BooleanField)
     * @type {boolean}
     */
    canModify: boolean;
    /**
     * **ID** (IDField)
     * @type {string}
     * @required true
     */
    id: string;
    /**
     * **Order** (IntField)
     * @description The order of this child in the list
     * @type {number}
     */
    order?: number;
    /**
     * **Created At** (TimeStampField)
     * @description The date and time this child was created
     * @type {number}
     * @required true
     */
    createdAt: number;
    /**
     * **Updated At** (TimeStampField)
     * @description The date and time this child was last updated
     * @type {number}
     * @required true
     */
    updatedAt: number;
    /**
     * **Parent** (ConnectionField)
     *
     * **EntryType** `entryPermission`
     * @type {string}
     * @required true
     */
    parent: string;
    /**
     * **Field Title** (DataField)
     * @type {string}
     */
    field__title?: string;
  }>;
};
export type EntryPermission = EntryBase<EntryPermissionFields> & {
  _name: "entryPermission";
  __fields__: EntryPermissionFields;
  /**
   * **Role** (ConnectionField)
   *
   * **EntryType** `userRole`
   * @description The user role this permission applies to
   * @type {string}
   * @required true
   */
  $role: string;
  /**
   * **Entry** (ConnectionField)
   *
   * **EntryType** `entryMeta`
   * @description The entry type this permission applies to
   * @type {string}
   * @required true
   */
  $entryMeta: string;
  /**
   * **Can View** (BooleanField)
   * @type {boolean}
   */
  $canView: boolean;
  /**
   * **Can Modify** (BooleanField)
   * @type {boolean}
   */
  $canModify: boolean;
  /**
   * **Can Create** (BooleanField)
   * @type {boolean}
   */
  $canCreate: boolean;
  /**
   * **Can Delete** (BooleanField)
   * @type {boolean}
   */
  $canDelete: boolean;
  /**
   * **ID** (IDField)
   * @type {string}
   * @required true
   */
  $id: string;
  /**
   * **Created At** (TimeStampField)
   * @description The date and time this entry was created
   * @type {number}
   * @required true
   */
  $createdAt: number;
  /**
   * **Updated At** (TimeStampField)
   * @description The date and time this entry was last updated
   * @type {number}
   * @required true
   */
  $updatedAt: number;
  /**
   * **Tags** (ArrayField)
   * @description Tags associated with this Entry Permission
   * @type {Array<any>}
   */
  $in__tags?: Array<any>;
  /**
   * **Role Title** (DataField)
   * @type {string}
   */
  $role__title?: string;
  /**
   * **Entry Title** (DataField)
   * @type {string}
   */
  $entryMeta__title?: string;
  isFieldModified(
    fieldKey: keyof {
      [K in keyof EntryPermission as K extends keyof EntryBase ? never : K]: K;
    },
  ): boolean;
  $fieldPermissions: ChildList<{
    /**
     * **Field** (ConnectionField)
     *
     * **EntryType** `fieldMeta`
     * @type {string}
     * @required true
     */
    field: string;
    /**
     * **Can View** (BooleanField)
     * @type {boolean}
     */
    canView: boolean;
    /**
     * **Can Modify** (BooleanField)
     * @type {boolean}
     */
    canModify: boolean;
    /**
     * **ID** (IDField)
     * @type {string}
     * @required true
     */
    id: string;
    /**
     * **Order** (IntField)
     * @description The order of this child in the list
     * @type {number}
     */
    order?: number;
    /**
     * **Created At** (TimeStampField)
     * @description The date and time this child was created
     * @type {number}
     * @required true
     */
    createdAt: number;
    /**
     * **Updated At** (TimeStampField)
     * @description The date and time this child was last updated
     * @type {number}
     * @required true
     */
    updatedAt: number;
    /**
     * **Parent** (ConnectionField)
     *
     * **EntryType** `entryPermission`
     * @type {string}
     * @required true
     */
    parent: string;
    /**
     * **Field Title** (DataField)
     * @type {string}
     */
    field__title?: string;
  }>;
};

type ApiGroupFields = {
  /**
   * **Group Name** (DataField)
   * @type {string}
   * @required true
   */
  groupName: string;
  /**
   * **Label** (DataField)
   * @type {string}
   * @required true
   */
  label: string;
  /**
   * **Description** (TextField)
   * @description A short description of the API group
   * @type {string}
   */
  description?: string;
  /**
   * **Extension Meta** (ConnectionField)
   *
   * **EntryType** `extensionMeta`
   * @description The extension this API group belongs to
   * @type {string}
   */
  extensionMeta?: string;
  /**
   * **API Group** (IDField)
   * @type {string}
   * @required true
   */
  id: string;
  /**
   * **Created At** (TimeStampField)
   * @description The date and time this entry was created
   * @type {number}
   * @required true
   */
  createdAt: number;
  /**
   * **Updated At** (TimeStampField)
   * @description The date and time this entry was last updated
   * @type {number}
   * @required true
   */
  updatedAt: number;
  /**
   * **Tags** (ArrayField)
   * @description Tags associated with this API Group
   * @type {Array<any>}
   */
  in__tags?: Array<any>;
  /**
   * **Extension Meta Title** (DataField)
   * @type {string}
   */
  extensionMeta__title?: string;
};
export type ApiGroup = EntryBase<ApiGroupFields> & {
  _name: "apiGroup";
  __fields__: ApiGroupFields;
  /**
   * **Group Name** (DataField)
   * @type {string}
   * @required true
   */
  $groupName: string;
  /**
   * **Label** (DataField)
   * @type {string}
   * @required true
   */
  $label: string;
  /**
   * **Description** (TextField)
   * @description A short description of the API group
   * @type {string}
   */
  $description?: string;
  /**
   * **Extension Meta** (ConnectionField)
   *
   * **EntryType** `extensionMeta`
   * @description The extension this API group belongs to
   * @type {string}
   */
  $extensionMeta?: string;
  /**
   * **API Group** (IDField)
   * @type {string}
   * @required true
   */
  $id: string;
  /**
   * **Created At** (TimeStampField)
   * @description The date and time this entry was created
   * @type {number}
   * @required true
   */
  $createdAt: number;
  /**
   * **Updated At** (TimeStampField)
   * @description The date and time this entry was last updated
   * @type {number}
   * @required true
   */
  $updatedAt: number;
  /**
   * **Tags** (ArrayField)
   * @description Tags associated with this API Group
   * @type {Array<any>}
   */
  $in__tags?: Array<any>;
  /**
   * **Extension Meta Title** (DataField)
   * @type {string}
   */
  $extensionMeta__title?: string;
  isFieldModified(
    fieldKey: keyof {
      [K in keyof ApiGroup as K extends keyof EntryBase ? never : K]: K;
    },
  ): boolean;
};

type ApiActionFields = {
  /**
   * **Action Name** (DataField)
   * @type {string}
   * @required true
   */
  actionName: string;
  /**
   * **Label** (DataField)
   * @type {string}
   * @required true
   */
  label: string;
  /**
   * **Description** (TextField)
   * @description A short description of the API action
   * @type {string}
   */
  description?: string;
  /**
   * **Api Group** (ConnectionField)
   *
   * **EntryType** `apiGroup`
   * @description The API group this action belongs to
   * @type {string}
   * @required true
   */
  apiGroup: string;
  /**
   * **API Action** (IDField)
   * @type {string}
   * @required true
   */
  id: string;
  /**
   * **Created At** (TimeStampField)
   * @description The date and time this entry was created
   * @type {number}
   * @required true
   */
  createdAt: number;
  /**
   * **Updated At** (TimeStampField)
   * @description The date and time this entry was last updated
   * @type {number}
   * @required true
   */
  updatedAt: number;
  /**
   * **Tags** (ArrayField)
   * @description Tags associated with this API Action
   * @type {Array<any>}
   */
  in__tags?: Array<any>;
  /**
   * **Api Group Title** (DataField)
   * @type {string}
   */
  apiGroup__title?: string;
};
export type ApiAction = EntryBase<ApiActionFields> & {
  _name: "apiAction";
  __fields__: ApiActionFields;
  /**
   * **Action Name** (DataField)
   * @type {string}
   * @required true
   */
  $actionName: string;
  /**
   * **Label** (DataField)
   * @type {string}
   * @required true
   */
  $label: string;
  /**
   * **Description** (TextField)
   * @description A short description of the API action
   * @type {string}
   */
  $description?: string;
  /**
   * **Api Group** (ConnectionField)
   *
   * **EntryType** `apiGroup`
   * @description The API group this action belongs to
   * @type {string}
   * @required true
   */
  $apiGroup: string;
  /**
   * **API Action** (IDField)
   * @type {string}
   * @required true
   */
  $id: string;
  /**
   * **Created At** (TimeStampField)
   * @description The date and time this entry was created
   * @type {number}
   * @required true
   */
  $createdAt: number;
  /**
   * **Updated At** (TimeStampField)
   * @description The date and time this entry was last updated
   * @type {number}
   * @required true
   */
  $updatedAt: number;
  /**
   * **Tags** (ArrayField)
   * @description Tags associated with this API Action
   * @type {Array<any>}
   */
  $in__tags?: Array<any>;
  /**
   * **Api Group Title** (DataField)
   * @type {string}
   */
  $apiGroup__title?: string;
  isFieldModified(
    fieldKey: keyof {
      [K in keyof ApiAction as K extends keyof EntryBase ? never : K]: K;
    },
  ): boolean;
};

type SystemSettingsFields = {
  /**
   * **Enable User Signup** (BooleanField)
   * @description Enable user signup for new accounts. Turn off to prevent new users from signing up.
   * @type {boolean}
   */
  enableSignup: boolean;
  /**
   * **Server Host** (URLField)
   * @description The host URL of the server. This is used for generating links and API endpoints.
   * @type {string}
   * @required true
   */
  serverHost: string;
};
export type SystemSettings = SettingsBase<SystemSettingsFields> & {
  _name: "systemSettings";
  __fields__: SystemSettingsFields;
  /**
   * **Enable User Signup** (BooleanField)
   * @description Enable user signup for new accounts. Turn off to prevent new users from signing up.
   * @type {boolean}
   */
  $enableSignup: boolean;
  /**
   * **Server Host** (URLField)
   * @description The host URL of the server. This is used for generating links and API endpoints.
   * @type {string}
   * @required true
   */
  $serverHost: string;
  isFieldModified(
    fieldKey: keyof {
      [K in keyof SystemSettings as K extends keyof SettingsBase ? never : K]:
        K;
    },
  ): boolean;
};

type AuthSettingsFields = {
  /**
   * **Google Client ID** (TextField)
   * @description The client ID for Google authentication.
   * @type {string}
   */
  googleClientId?: string;
  /**
   * **Google Client Secret** (PasswordField)
   * @description The client secret for Google authentication.
   * @type {string}
   */
  googleClientSecret?: string;
  /**
   * **Hostname** (URLField)
   * @description The hostname for the server used to construct the redirect URL.
   * @type {string}
   */
  hostname?: string;
};
export type AuthSettings = SettingsBase<AuthSettingsFields> & {
  _name: "authSettings";
  __fields__: AuthSettingsFields;
  /**
   * **Google Client ID** (TextField)
   * @description The client ID for Google authentication.
   * @type {string}
   */
  $googleClientId?: string;
  /**
   * **Google Client Secret** (PasswordField)
   * @description The client secret for Google authentication.
   * @type {string}
   */
  $googleClientSecret?: string;
  /**
   * **Hostname** (URLField)
   * @description The hostname for the server used to construct the redirect URL.
   * @type {string}
   */
  $hostname?: string;
  isFieldModified(
    fieldKey: keyof {
      [K in keyof AuthSettings as K extends keyof SettingsBase ? never : K]: K;
    },
  ): boolean;
};

type EmailSettingsFields = {
  /**
   * **Final Redirect** (URLField)
   * @description The final url to redirect to after Google OAuth completes
   * @type {string}
   */
  redirectFinal?: string;
  /**
   * **Default Send Account** (ConnectionField)
   *
   * **EntryType** `emailAccount`
   * @description The default email account to use for sending emails
   * @type {string}
   */
  defaultSendAccount?: string;
  /**
   * **Default Send Account Title** (EmailField)
   * @description The email account to send emails from
   * @type {string}
   */
  defaultSendAccount__title?: string;
};
export type EmailSettings = SettingsBase<EmailSettingsFields> & {
  _name: "emailSettings";
  __fields__: EmailSettingsFields;
  /**
   * **Final Redirect** (URLField)
   * @description The final url to redirect to after Google OAuth completes
   * @type {string}
   */
  $redirectFinal?: string;
  /**
   * **Default Send Account** (ConnectionField)
   *
   * **EntryType** `emailAccount`
   * @description The default email account to use for sending emails
   * @type {string}
   */
  $defaultSendAccount?: string;
  /**
   * **Default Send Account Title** (EmailField)
   * @description The email account to send emails from
   * @type {string}
   */
  $defaultSendAccount__title?: string;
  isFieldModified(
    fieldKey: keyof {
      [K in keyof EmailSettings as K extends keyof SettingsBase ? never : K]: K;
    },
  ): boolean;
};

type OnboardingFields = {
  /**
   * **Enable Onboarding** (BooleanField)
   * @description Enable or disable onboarding for new users
   * @type {boolean}
   */
  enabled: boolean;
};
export type Onboarding = SettingsBase<OnboardingFields> & {
  _name: "onboarding";
  __fields__: OnboardingFields;
  /**
   * **Enable Onboarding** (BooleanField)
   * @description Enable or disable onboarding for new users
   * @type {boolean}
   */
  $enabled: boolean;
  isFieldModified(
    fieldKey: keyof {
      [K in keyof Onboarding as K extends keyof SettingsBase ? never : K]: K;
    },
  ): boolean;
};

export interface EntryMap {
  user: User;
  userSession: UserSession;
  account: Account;
  inTaskGlobal: InTaskGlobal;
  inTask: InTask;
  cloudFile: CloudFile;
  globalCloudFile: GlobalCloudFile;
  email: Email;
  emailAccount: EmailAccount;
  emailTemplate: EmailTemplate;
  onboardingStep: OnboardingStep;
  userRole: UserRole;
  entryMeta: EntryMeta;
  extensionMeta: ExtensionMeta;
  fieldMeta: FieldMeta;
  entryAction: EntryAction;
  entryPermission: EntryPermission;
  apiGroup: ApiGroup;
  apiAction: ApiAction;
}
export interface SettingsMap {
  systemSettings: SystemSettings;
  authSettings: AuthSettings;
  emailSettings: EmailSettings;
  onboarding: Onboarding;
}
export type EntryName = Exclude<keyof EntryMap, symbol | number>;
export type SettingsName = Exclude<keyof SettingsMap, symbol | number>;
