name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - name: Replace $CLOUD_VERSION with deno.json version
        run: |
          sed -i "s/\$CLOUD_VERSION/$(jq -r '.version' deno.json)/" src/extension/core-extension.ts
      - name: Publish package
        run: npx jsr publish --allow-dirty
